[project]
name = "transitions-in-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "evosax",
    "gymnax>=0.0.9",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
evosax = { git = "https://github.com/RobertTLange/evosax.git", rev = "main" }
